sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
after_success:
  - "lander --pdf DMTN-051*.pdf --upload --lsstdoc DMTN-051.tex --env=travis --ltd-product $PRODUCT --handle $HANDLE"
env:
  global:
    # Handle needs to be explicitly set until https://github.com/lsst-sqre/metasrc handles LaTeX inputs
    - HANDLE="DMTN-051"
    - PRODUCT="dmtn-051"
    - secure: "fpPpIs359l7bfY/a0xlOo3ucqgujb4sL6sRiiRo/5ErYukDz/5BlmS5LDW9M4lchYPuXtpXnvFeRL17d5zVHxLZnDj0bm9tut26tbzPsmQvfg+8y/6ggOXbsYa4IbutOsQa4oP6BrrApW1g0AXeG5zpO3mSmVRCWUrobBVX/TMBizb2/1C/QIDa8/twIO3dDRM+mw5zTMQfaSZcXTeO4pV6eZVKSXFkfD70swMJVQqNWrzhxJcft+V3PLV9Nt0zfnUgpin10dBEPhc6g9ONqZel7isfT1J+5YVHVr4JTvSkltIWiteCfwpz5RleN/1W6SHcxvLQotP/xRJlzdzL0UBExlGaX0H4HorV5acZUZZTMZk7E3NZWBm+E2EuohF8Y+vwANb9wcWhtZ2dGsH5Fqi0kJUOIF6ZIE0JVXq+HXjuWBB91MwPBrV1AS9n37H0Ce5icJEIUprKo7zf50exeHcw44y0jb831617Cl/5yj7IBuSe5eTufoyHypocMN60zMO4VpoHfLIL+80SKXzWwYZAKLWcauPrDPoSraha/MFxxb+DJ7itnYWe7dX9kA+l9GmW1lL42f12LMuVMW/CcaDdZ+POtRz80Qlv6YY+blRWKP5UZ/S/4DcyC/WVDyefoLE3nVrHaq/R0XpZwb+Aqxxttu5Nz6k/XeKsEmAFXYIE="
    - secure: "Ma4xNPkK/MbwEVOrKuXjZbCjENl8xcRgatmLjMW34Ldj9IkTJpIYeitC8WCm2+bLW+IZgi5RJgu2VudoAt3ZV57aHEbP/UwAdKL/ZP/b9I8UrU0knrKSTpKMMGF6w4RL7JwbsPL4RSErwCjjYk3JRu4wKd6mArKiaWfDhX7ZptaJU3LARz3WtvtXnmvjwsUbXqN8Wh9fqr00WTSZJkViaD57xFxmdc7om/28Tqkr/+ctildZhHggx8EmA6PJPfz6+IWtSyMmKDvbolPUsnLy1UYSQTjEOshCXtO16a2djUXRRUJEU6wxGteF4qnTgrHADihu9VstXcmJPHdQOvAZVfxoe6cIMXHnxRTj8CzDpPABmAGesO54jGw/9ELK77DuDKycV9dfMr9gIB7FScusUXOeEDKqjeWPqWa187/FAQGsJ+Iq5DJii46ucC/QYrwNDo122OqHYmOdADUOn3HchqHoXGLQEIFnS/PBx2tVUcEE9vaidgrl02wbIcPd5bQ34GYedIbO+9Uasu1VaYBqSJQhvOnK6gH8I57647P+oZbYDYvTym1d/X3Xd2by/gqg6PLl3CavsyTGaL/6DfI4zPmb62MG756rLr24YqCBgBS0SOSfzeSk7KE0XJnkgJCRdpTlVdRQw90LpSGUzP69QYpZAiIeFvljJdNPv8nPnxo="
